### Hent selskapsdata fra Brreg
GET http://localhost:8080/api/company-data/996281248

### Opprett sak
POST http://localhost:8080/api/cases
Content-Type: application/json

{
  "title": "Forhandling 2026",
  "negotiationYear": 2026,
  "orgNumber": "996281248"
}

### Hent alle saker
GET http://localhost:8080/api/cases

### Hent én sak
GET http://localhost:8080/api/cases/1

### Analyser sak
GET http://localhost:8080/api/cases/1/analyze